os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode10.2

cache:
  directories:
    - ${HOME}/.swiftenv/

install:
  - eval "$(cat install_swift.sh)"
script:
  - swift run