[build]
  command = "export URL=\"https://swift.org/builds/swift-5.0-release/ubuntu1604/swift-5.0-RELEASE/swift-5.0-RELEASE-ubuntu16.04.tar.gz\"; eval \"$(curl -sL https://swiftenv.fuller.li/install.sh)\" && swift run"
  publish = "_site"
